name = "IbnrClaims"
uuid = "9ac2770f-f924-4de4-828c-1183aeafeae2"
authors = ["Jose Diaz <jose.diaz.cisternas@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
Distributions = "0.25"
Documenter = "0.27.6"
DocumenterTools = "0.1.13"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
